"""Command line entrypoint."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from envguard import __version__
from envguard.report import Report, build_report

RESET, BOLD, DIM = "\033[0m", "\033[1m", "\033[2m"
RED, YELLOW, GREEN, CYAN = "\033[31m", "\033[33m", "\033[32m", "\033[36m"


class Palette:
    def __init__(self, enabled: bool) -> None:
        self.enabled = enabled

    def __call__(self, text: str, code: str) -> str:
        return f"{code}{text}{RESET}" if self.enabled else text


def render_text(report: Report, c: Palette) -> str:
    lines: list[str] = []
    add = lines.append

    add(c(f"envguard {__version__}", BOLD) + c(f"  {report.root}", DIM))
    source = report.env_file.name if report.env_file else "none found"
    add(c(f"  reference file: {source}", DIM))
    add("")

    if report.missing:
        add(c(f"✗ {len(report.missing)} variable(s) used but never declared", RED))
        for name in report.missing:
            refs = report.references_for(name)
            where = ", ".join(r.location for r in refs[:3])
            more = f" (+{len(refs) - 3} more)" if len(refs) > 3 else ""
            add(f"    {c(name, BOLD)}  {c(where + more, DIM)}")
        add("")

    if report.secrets:
        add(c(f"✗ {len(report.secrets)} possible hardcoded secret(s)", RED))
        for s in report.secrets:
            tag = c("HIGH", RED) if s.confidence == "high" else c("MED ", YELLOW)
            add(f"    [{tag}] {s.rule}  {c(s.location, DIM)}  {s.preview}")
        add("")

    if report.committed_env_files:
        add(c(f"✗ {len(report.committed_env_files)} real .env file(s) in the tree", RED))
        for path in report.committed_env_files:
            add(f"    {path}  {c('← make sure this is gitignored', DIM)}")
        add("")

    if report.filled_example:
        add(c(f"! {len(report.filled_example)} example value(s) look real, not placeholder", YELLOW))
        add(f"    {', '.join(report.filled_example)}")
        add("")

    if report.unused:
        add(c(f"· {len(report.unused)} declared but unused (dead config)", CYAN))
        add(f"    {', '.join(report.unused)}")
        add("")

    if report.issue_count == 0:
        add(c("✓ no issues found", GREEN))
    add(c(
        f"  {len(report.used)} used · {len(report.declared)} declared · "
        f"{report.issue_count} issue(s)", DIM,
    ))
    return "\n".join(lines)


def render_markdown(report: Report) -> str:
    d = report.to_dict()
    s = d["summary"]
    out = [
        "## envguard report",
        "",
        f"`{report.root}` — **{s['issues']}** issue(s) across {s['variables_used']} variable(s).",
        "",
        "| check | count |",
        "| --- | --- |",
        f"| Missing from example | {s['missing']} |",
        f"| Possible secrets | {s['secrets']} |",
        f"| Unused declarations | {s['unused']} |",
    ]
    if report.missing:
        out += ["", "### Missing", ""]
        out += [f"- `{m['name']}` — used at {', '.join(f'`{loc}`' for loc in m['used_at'][:3])}"
                for m in d["missing"]]
    if report.secrets:
        out += ["", "### Possible secrets", ""]
        out += [f"- **{x['confidence']}** `{x['rule']}` at `{x['location']}` (`{x['preview']}`)"
                for x in d["secrets"]]
    return "\n".join(out) + "\n"


def generate_example(report: Report) -> str:
    """Emit a .env.example that matches what the code actually reads."""
    lines = ["# Generated by envguard. Values are placeholders - never commit real ones.", ""]
    by_name: dict[str, list[str]] = {}
    for ref in report.references:
        by_name.setdefault(ref.name, []).append(ref.location)
    for name in sorted(by_name):
        lines.append(f"# used at: {by_name[name][0]}")
        existing = report.declared.get(name)
        lines.append(f"{name}={existing if existing else 'changeme'}")
        lines.append("")
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="envguard",
        description="Catch .env drift and hardcoded secrets before they ship.",
    )
    p.add_argument("path", nargs="?", default=".", help="directory to scan (default: .)")
    p.add_argument("-e", "--env-file", type=Path, help="reference file (default: auto-detect .env.example)")
    p.add_argument("-f", "--format", choices=("text", "json", "markdown"), default="text")
    p.add_argument("--no-secrets", action="store_true", help="skip the secret scanner")
    p.add_argument("--strict", action="store_true", help="also fail on unused declarations")
    p.add_argument("--init", action="store_true", help="write a .env.example derived from the code")
    p.add_argument("--no-color", action="store_true")
    p.add_argument("-V", "--version", action="version", version=f"envguard {__version__}")
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = Path(args.path)
    if not root.exists():
        print(f"envguard: no such path: {root}", file=sys.stderr)
        return 2

    report = build_report(root, env_file=args.env_file, check_secrets=not args.no_secrets)

    if args.init:
        target = root / ".env.example"
        target.write_text(generate_example(report), encoding="utf-8")
        print(f"wrote {target} ({len(report.used)} variables)")
        return 0

    if args.format == "json":
        print(report.to_json())
    elif args.format == "markdown":
        print(render_markdown(report), end="")
    else:
        colour = sys.stdout.isatty() and not args.no_color
        print(render_text(report, Palette(colour)))

    failed = report.issue_count > 0 or (args.strict and bool(report.unused))
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
